### ISSUE TITLE
Obfuscated code

### ISSUE THREAD

**Issue by lujianzhao** [konmik/nucleus#126]
release{
minifyEnabled true
}
Proguard  Error.
How should the confusion file be written?

java.lang.InstantiationException: java.lang.Class<com..db.c.a> has no zero argument constructor
11-25 14:43:10.591 11067-11067/?  at java.lang.Class.newInstance(Native Method)

**Comment by TWiStErRob** [comment]
Sounds like you need to keep the constructor for whatever `com.db.c.a` was, something like:
```proguard
-keepclassmembers class com........ {
    <init>();
}
```
(replace `com........` with original class name)

**Comment by lujianzhao** [comment]
Thank You！

**Comment by yankeppey** [comment]
I also had the similar crashes in some Presenters. 
My explanation is that since there is no place for Presenter constructor to be called directly (it's only called from Class.newInstance()), Proguard can mark it as private.

I added the following proguard rule:

> -keepclassmembers class * extends nucleus.presenter.Presenter {
>     <init>();
> }
> 

I think it would be useful to add this rule into Nucleus `README.md`. @konmik , what do you think?

**Comment by TWiStErRob** [comment]
@yankeppey `<init>` (I'm guessing) is parsed as HTML, you need to escape it with `\`

**Comment by konmik** [comment]
I think it is a great idea! I personally newer worked with ProGuard, so your help is very appreciated!

**Comment by TWiStErRob** [comment]
@konmik consider [android.defaultConfig.consumerProguardFile](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ProductFlavor.html#com.android.build.gradle.internal.dsl.ProductFlavor:consumerProguardFile(java.lang.Object))

**Comment by konmik** [comment]
Added to readme, thank you! :)
