### ISSUE TITLE
Make Presenter independent of Android stuff (Bundle)

### ISSUE THREAD

**Issue by fernandocamargoti** [konmik/nucleus#26]
As someone asked you in your article, I think Presenter shouldn't have any Android stuff. So, the onSave and onCreate should use Map or something else.

**Comment by konmik** [comment]
Hi, @fernandocamargoti !

Since those times, Android Tools Development Team released unit testing support, so now we don't have a need to split out Bundle class - it can be easily mocked.

If we need to reuse a presenter on another non-android system, we will just need to implement Bundle class. Currently I do not see how I can replace Bundle with Map without sacrificing Icepick-like tools.

**Comment by fernandocamargoti** [comment]
Understood.

Well, I'm gonna run my tests using the Robolectric runner. I think that the gain was to create pure java unit tests for the Presenter (without Robolectric), but the gain may be too small for a API break and the impossibility of using Icepick.

Thank you for your attention.
