### ISSUE TITLE
Dagger2 and Nucleus

### ISSUE THREAD

**Issue by scriptacus** [konmik/nucleus#33]
Not so much an issue as a question of practices:

Most Dagger 2 examples that I see rely on a "context" (generally from the Activity or Application) to get/create components and modules.  Presenters don't inherently have a context, and the Presenter itself can have a different lifecycle from it's Activity.  This makes me hesitant to use the Activity context.  I could get the application context but based on what I have read that seems like bad practice.  In my particular case I'm making use of a factory to create my Presenter, so I don't think constructor injection in the Presenter class can work, and integrating Dagger into the factory strikes me as a bit odd.

How would you recommend handling DI in a case like this, using Dagger 2?  (I'm currently leaning towards just getting/using the application context, but that feels sloppy)

**Comment by konmik** [comment]
Hi, I always use Application context. Have no idea why someone can shy to use it. Just keep in mind that it can disappear during process reset, as anything else disappears. Dagger will reconstruct all objects when needed.

**Comment by konmik** [comment]
An addition, because this can be unclear to someone: that solutions which rely on passing Dagger context with activity`s `getSystemService` or pass it with `getLastNonConfigurationInstance`, will lose the Dagger context during a process reset as well.

Process reset is a process reset - *everything* disappear. And after that, when the user navigates back, Android restores activities from saved state passing state into onCreate(Bundle bundle)`.
