### ISSUE TITLE
Prevent subclassing

### ISSUE THREAD

**Issue by JoanZapata** [konmik/nucleus#4]
It seems the subclassing of ```NucleusActivity``` is the only option for now. I can see from your code that all the logic actually lies in PresenterHelper, but it would probably be a little bit verbose to use it in all activities. I guess that's why you introduced ```NucleusActivity```.

Starting from API 14 we can register [callbacks](http://goo.gl/QuzuI) on activity lifecycle, so the subclassing could probably be replaced by a simple call to something like ```Nucleus.bind(this)``` in the ```onCreate()``` of each activity.

What do you think?

EDIT: It would probably be a `second option` rather than a replacement, since it wouldn't be compatible with API < 14.

**Comment by konmik** [comment]
You need to have a field in activity so activity can easily access presenter, and that field should also be accessible from the code that controls the presenter's lifecycle. This is encapsulation break. Otherwise you will need to implement NucleusAcitivtyManager, and access presenter from that manager, so instead of getPresenter() you will have to write Nucleus.getPresenter(this) every time. All of this looks like overcomplication to me. Inheritance just works.

There are also uniformity considerations. Right now you can be sure that all presenters and views in Nucleus work the same way, so it is easy to understand the whole picture.

If you will create an implementation for Manager, I would like to see it anyway, probably you will find an elegant solution :)

**Comment by JoanZapata** [comment]
> Inheritance just works.

Until another lib decides to do the same.

> You will need to have a field in activity so activity can easily access presenter, and that field should also be accessible from the code that controls the presenter's lifecycle. This is encapsulation break. Otherwise you will need to implement NucleusAcitivtyManager, and access presenter from that manager, so instead of getPresenter() you will have to write Nucleus.getPresenter(this) every time. All of this looks like overcomplication to me.

The proper way would probably be to inject the presenter in a ```@Presenter``` or ```@Inject``` annotated field during the ```Nucleus.bind(this)``` call.

> There are also uniformity considerations. Right now you can be sure that all presenters and views in Nucleus work the same way, so it is easy to understand the whole picture. (There are also NucleusLayout and NuleusFragment classes).

Good point.

> If you will create an implementation for Manager, I would like to see it anyway, probably you will find an elegant solution :)

I'll really try to get my hands on Flow/Mortar for my next project, but yeah, I'll keep you posted if I do. :)

**Comment by konmik** [comment]
| Until another lib decides to do the same.

I am aware of such possibility, this is why Nucleus is not tied to any specific view class - you can just copy/paste code that controls Presenter.
