### ISSUE TITLE
getView is null in onActivityResult()

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#48]
Inside my fragment, I call startActivityForResult where I launch a camera activity, and I get back a result and ask the presenter to do some work on the returned data. When the presenter calls getView(), it returns a null object.

Seems to be similar to this issue: https://github.com/konmik/nucleus/issues/35

For now I am doing this (the suggestion from issue #35) : 
``` Java
protected void onActivityResult(int requestCode, int resultCode, Intent intent) {

     getPresenter().takeView(this);
     getPresenter().doXYZ();

}
```
I am using nucleus ver. 2.0.3

**Comment by konmik** [comment]
Hi, this is the intended behavior.

* Presenter has a reference to View only between `onResume`/`onPause`.
* View has a reference to Presenter any time it want, but it is highly advisable to not request for presenter before the view state has been restored.
* `onActivityResult` happens *before* `onResume`, so Presenter does not have View attached.

The usual workflow is to ask Presenter for an *asynchronous* operation and return results back when View becomes available using `deliveryXX` mechanics, so this is not normally a problem.

Yes, you can call `onTakeView` but beware of consequences. Delivery methods can be fired one more time.

**Comment by sreejithraman** [comment]
Isn't the idea behind MVP to decouple logic code? So, say I get back a bitmap that i need to manipulate from onActivityResult, shouldn't that go inside the presenter? What do you mean by delivery methods can be fired one more time? What exactly are delivery methods?

**Comment by twig** [comment]
I have also run into [this problem with onActivityResult()](https://www.reddit.com/r/androiddev/comments/3rehwl/how_to_transition_from_traditional_android/cwnfiau).

If this is intended behaviour, please mention it in the documentation (or make it clearer since I haven't run into it yet) and perhaps list a few possible workarounds.

**Comment by konmik** [comment]
@sreejithraman This depends on implementation. Nucleus and Mortar have the kind of implementation that allows for background task continuation. Other libraries allow to to write a better coupled V-P so you can put more logic inside of presenter. 

There is no a clean and consistent way for MVP approach on Android because Android SDK is not consistent by itself. All that lifecycles, state handling, god objects - you can put into examples of how to NOT write you code. Never. So MVP on Android is quite hackish. Some libraries can help with background task continuation, some can help with extracting logic out of views, but there are no libraries that can do both well. Nucleus is a kind of library that you can't use to easily create thin views.

`delivery` methods are https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/RxPresenter.java#L213
and 
https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/RxPresenter.java#L152
and other that start with `deliver`. `restartable` methods use delivery methods internally.

Every time you call `onTakeView`, `RxPresenter` tries to update View data.

**Comment by konmik** [comment]
@twig done!

https://github.com/konmik/nucleus/commit/29d146d7537ecbe0ef25b9a00b7de7d3b925e34f

**Comment by twig** [comment]
Cheers @konmik

**Comment by sreejithraman** [comment]
@konmik so then with your library, what is the general pattern i should try to follow for putting logic inside views (when would you say it is appropriate to delegate logic to the Presenter and when would you say the View should handle it)? Is there a delivery method that I can wrap `getView().doXYZ()` in (is this even a good idea)? 

And if I understand correctly with the restartables, `restartable()` will only "deliver" if you explicitly call `start()` and only methods like `restartableFirst()`, `restartableLatestCache()` will "deliver" when `onTakeView()` is called. Is that right? If so, is there a `deliver` method that will only `deliver` once and not every time `onTakeView()` is called?

**Comment by konmik** [comment]
@sreejithraman 

1.

I put View logic inside of Views. Sounds logical.

Presenter is used to access and prepare data. Business rules also take place inside of presenter.

Model is where the data is being kept - network, database interface and such.

2. Yes, it only starts when you explicitly call it to start.

Yes, there is such method, it is called `deliverFirst()`.

**Comment by sreejithraman** [comment]
@konmik Sorry, one last question. If `deliverFirst()` delivers only once, does that apply to `restartableFirst()` too? If so what is difference between restartableFirst() and restartable()? In the docs, you said "shortcut that can be used instead of combining together". I don't quite get that.

**Comment by konmik** [comment]
Yes, `restartableFirst` is named after `deliverFirst`. All restartableXX methods mirror corresponding deliverXX methods.

**Comment by konmik** [comment]
`restartable` does not have a delivery method, you can supply your own subscription.
