### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by IgorGanapolsky** [konmik/nucleus#5]
Can you please give an example of using Nucleus with Material Design - like Toolbar (with tabs)?  Right now your sample has hard-coded tabs and no Toolbar.

**Comment by konmik** [comment]
Nucleus has no relation to design, at all. :)

I do not understand why are you asking this.

The example is just an example of using Nucleus, not how to build your entire application with all possible android components.

**Comment by IgorGanapolsky** [comment]
@konmik It would be nice to look at a sample app and say "aha, this is something I can use or build on top of".  As it is, it looks ugly and outdated.  Hence it may turn developers away.

**Comment by konmik** [comment]
Slow tabs? What do you mean? How simple views can be slow? 8-) They are not slow. I just decided to actually switch them AFTER the response from the server arrives. This is not because I do not use Toolbar, this is intentional behavior. You could do the same with Toolbar, I think.

P.S. Toolbar is outdated from the beginning. It is just a buggy cover around simple views, it gives no any advantages over LinearLayout. I've tried Toolbar a couple of times - found three bugs, used two workarounds for simple tasks. However, it is much more reliable than ActionBar, so I understand why people prefer it now. :D

P.P.S. I think, there can not be an example that someone can use to build his application on top of. Every application is different, every developer has a different set of preferred technologies and libraries. We're in Android area have an exploding growth of technologies right now. Everything I will name a "template" will become obsolete a couple of months later.

**Comment by IgorGanapolsky** [comment]
I understand your points.  By 'slow' I mean click the [fake] tab in your appand wait 2 seconds for it to switch.  That is unacceptable from a UI standpoint, and will subconsciously convince the user that there is something wrong with the app.

**Comment by rharter** [comment]
@IgorGanapolsky To answer your question, normally when using tabs with a toolbar, you would use something like Fragments for the contents of each tab.  

While the sample doesn't specifically show using Nucleus with Fragments, I think it's fairly simple to extrapolate the use of NucleusActivity to NucleusFragment, then you can simply use it exactly like the sample.

If you're using plain old Views as your tab contents, simply use NucleusLayout as your parent class.

@konmik is right that how to use tabs is outside the scope of a simple example.  If you want more information on that, check out this article, and simply replace the Fragment implementations they use with Presenter driven ones from Nucleus.

**Comment by konmik** [comment]
@IgorGanapolsky the example is not intended to impress an end user or to shock a developer with tremendous complexity. A developer, however, should understand why the "lag" is happening.

**Comment by IgorGanapolsky** [comment]
@konmik There should never be a lag when going from tab to tab.  I have never seen this in any Android app (and i've been doing Android for 5 years).  So I'm sorry, but I disagree that bad functionality in a demo app serves a useful purpose.
