### ISSUE TITLE
deliverLatestCache() example

### ISSUE THREAD

**Issue by devilmac** [konmik/nucleus#51]
Hi konmik,
I'm using this library into my app and I find it great and easy to use. I have a little problem with deliverLatestCache() method. You said that:

``deliverLatestCache() is the same as deliverLatest() but in addition it will keep the latest result in memory and will re-deliver it when another instance of a view becomes available (i.e. on configuration change). If you don't want to organize save/restore of a request result in your view (in case if a result is big or it can not be easily saved into Bundle) this method will allow you to make user experience better.
``

and I'm trying to get this latest result but I don't understand what I have to do with it. Can you make an example of use for this method?

Thanks a lot.

**Comment by inorichi** [comment]
In your subscription you should call a method of your view that updates the data. When you rotate the screen, the last result will be given again to the view, without repeating the query or network call or whatever. You don't have to do anything else.

You can use restartable*, a pseudocode example here: https://github.com/konmik/nucleus/issues/42#issuecomment-149006788

And a real example:

MyPresenter:

    private static final int GET_MY_DATA = 1;
    
    @Override
    protected void onCreate(Bundle savedState) {
        super.onCreate();

        restartableLatestCache(GET_MY_DATA,
                () -> Observable.just(1)
                            .subscribeOn(Schedulers.io())
                            .observeOn(AndroidSchedulers.mainThread()),
                (view, data) -> {
                    view.doSomething(data);
                }, (view, error) -> {
                    view.doSomethingOnError(error);
                });
    
        start(GET_MY_DATA);
    }

Or you can use the deilver* methods, for example (I'm using lambdas):

MyPresenter:

    @Override
    protected void onCreate(Bundle savedState) {
        super.onCreate();

        Observable.just(1)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .compose(deliverLatestCache())
                .subscribe(
                        split((view, data) -> {
                            view.doSomething(data);
                        }),
                        split((view, error) -> {
                            view.doSomethingOnError(error);
                        }));
    }

I would use the restartable approach. It allows you to start the observable whenever you want, with the start(x) method, so that you can provide some parameters to the query first. Just make sure you are not restarting the observable when a configuration change occurs in order to take advantage of these deliver* methods.

**Comment by konmik** [comment]
@devilmac , did @inorichi anwer your question? You can close the issue if so.
