### ISSUE TITLE
How to find if a restartable is started already?

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#63]
Is there a method that I can call to see if a certain restartable is started? I have a restartable that is paging, and normally I would just start it in the `onCreate()` of the `presenter` but since I need arguments passed to the activity, I have to call a method in the `onCreate()` of the `activity`. Now when I rotate the device, the activity is recreated and goes through the whole `onCreate()` and restarts the restartable. So, I put a boolean check to see if restartable has already started like so:

```java
public void fetchItems(String parentItemId){
        if(!hasStartedPaging) {
            rxPager = new RxPager();
            registerFetchItemsFromServerRestartable(parentItemId); // I just register a restartableReplay 
            start(RESTARTABLE_ID);
            hasStartedPaging = true;
        }
}
```

Is that how you would recommend doing this or can I replace the `hasStartedPaging` variable with something that lets me check if a restartable is already started? Or am I completely doing this wrong?

**Comment by inorichi** [comment]
You can start it when the bundle is null in your activity:

    if (savedInstanceState == null) {
        getPresenter().fetchItems(id);
    }

If you still want to know if a restartable is running, you will have to copy this class to your project https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/RxPresenter.java and add a method like this:

    public boolean isSubscribed(int restartableId) {
        Subscription s = restartableSubscriptions.get(restartableId);
        return s != null && !s.isUnsubscribed();
    }

**Comment by konmik** [comment]
It looks like a good idea to include `isSubscribed` into the next version. Thanks, @inorichi !

**Comment by sreejithraman** [comment]
@inorichi Correct me if I am wrong, but I can't do 
```java
if (savedInstanceState == null) {
    getPresenter().fetchItems(id);
}
```
after a crash because, the savedInstanceState will not be null and the presenter also would be recreated, right?

**Comment by inorichi** [comment]
After a process restart, the restartable will restart itself (as it's name says), that's why you should store that `parentItemId` in the presenter's bundle so that you don't get a NPE when accessing it.

[The wiki](https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android#best-practices) recommends you to use Icepick for saving/restoring instances.

Then you declare a variable with saved state in your presenter like so: `@State String parentItemId`. In your `fetchItems` method you add `this.parentItemId = parentItemId` and everything will work fine.

[This answer](https://github.com/konmik/nucleus/issues/42#issuecomment-149006788) can help you understanding how restartables work too.
