### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by CarlosEsco** [konmik/nucleus#65]
Simple question with nucleus what is the ideal design process for doing the following:

long click list, remove item, update view

currently i  do something like follows

view see click sends position -> presenter receives position updates data stops restartable, starts restartable

is there another way to rerun the initial restartable?  Should i be doing this differently?

**Comment by konmik** [comment]
Hi, you first need to have a some kind of storage. If you keep the list in a database then I would just update the database (remove the item) and then set some RxJava callback to cause the list to be re-fetched.

If for some reason you keep the list in-memory... it is up to your convenience. I need more info on what are you going to do when you remove the item. Do you post something to the server?

**Comment by cargo8005** [comment]
My restartable loads a json from sharedprefs and populates a list. 

In the view the user then has the option to remove/add objects from their view.  Which in turn goes to the presenter and  writes back to the sharedpref and repopulates the listview.

because my restartable does everything i need without repeating code i was using stop(id) start(id) after the sharedpref gets updated, so that the shared pref is reread and the listview repopulated.

**Comment by konmik** [comment]
OK,

first of, I think you may probably do not need to call stop(id)

I would extract shpref into a singleton and set a callback on it (beware of http://stackoverflow.com/questions/3799038/onsharedpreferencechanged-not-fired-if-change-occurs-in-separate-activity bug).

So when it gets updated I would deliverLatestCache() updated data from it into Activity. something like (pseudocode):

``` java
     presenter onCreate() {

          add(shprefObservable().
                 .map(parse)
                 .observeOn(mainthread())
                 .compose(deliverLatestCache())
                 .subscibe(split(activity::onNewData));
    }
```
